name: guiddiffsbdd
channels:
  - anaconda
  - conda-forge
  - nvidia
  - pkgs/main
  - pyg
  - pytorch
dependencies:
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - biopython=1.79
  - blas=1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.16.0
  - certifi=2025.10.5
  - cffi=1.15.1
  - charset-normalizer=3.4.4
  - click=8.2.1
  - comm=0.2.1
  - contourpy=1.3.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - cycler=0.11.0
  - debugpy=1.8.16
  - decorator=5.2.1
  - docker-pycreds=0.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - filelock=3.17.0
  - fontconfig=2.14.1
  - fonttools=4.60.1
  - freetype=2.13.3
  - fsspec=2025.7.0
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glib=2.69.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - greenlet=3.2.4
  - icu=70.1
  - idna=3.7
  - imageio=2.21.2
  - ipykernel=6.30.1
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libffi=3.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libiconv=1.18
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libprotobuf=3.20.3
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lightning-utilities=0.15.2
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - numexpr=2.11.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openbabel=3.1.1
  - openjpeg=2.5.4
  - openssl=1.1.1w
  - packaging=25.0
  - pandas=2.2.2
  - parso=0.8.4
  - pathtools=0.1.2
  - pcre=8.45
  - pexpect=4.9.0
  - pillow=11.1.0
  - pip=24.2
  - pixman=0.46.4
  - platformdirs=4.3.7
  - promise=2.3
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - protobuf=3.20.3
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pycairo=1.23.0
  - pycparser=2.23
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-lightning=1.8.4
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.2
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - rdkit=2022.03.2
  - readline=8.3
  - reportlab=4.4.3
  - requests=2.32.5
  - scipy=1.13.1
  - seaborn=0.13.2
  - sentry-sdk=2.18.0
  - setproctitle=1.3.6
  - setuptools=80.9.0
  - shortuuid=1.0.13
  - six=1.17.0
  - smmap=5.0.2
  - sqlalchemy=2.0.43
  - sqlite=3.50.2
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.8.0
  - tensorboardx=2.2
  - tk=8.6.15
  - torchmetrics=1.4.2
  - torchtriton=2.0.0
  - tornado=6.5.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wandb=0.13.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - Deprecated==1.2.18
    - Farama-Notifications==0.0.4
    - Flask==3.1.1
    - GitPython==3.1.44
    - Jinja2==3.1.6
    - SQLAlchemy==2.0.41
    - amqp==5.3.1
    - annotated-types==0.7.0
    - billiard==4.2.1
    - blinker==1.9.0
    - celery==5.5.2
    - charset-normalizer==3.4.2
    - click==8.2.1
    - click-didyoumean==0.3.1
    - click-plugins==1.1.1
    - click-repl==0.3.0
    - cloudpickle==3.1.1
    - contourpy==1.3.2
    - cycler==0.12.1
    - databricks-sdk==0.54.0
    - docker==7.1.0
    - fastapi==0.115.12
    - flower==2.0.1
    - fonttools==4.58.0
    - gitdb==4.0.12
    - graphene==3.4.3
    - graphql-core==3.2.6
    - graphql-relay==3.2.0
    - greenlet==3.2.2
    - gunicorn==23.0.0
    - gym==0.26.2
    - gym-notices==0.1.0
    - gymnasium==1.2.0
    - h11==0.16.0
    - humanize==4.12.3
    - itsdangerous==2.2.0
    - joblib==1.5.1
    - kiwisolver==1.4.8
    - kombu==5.5.3
    - matplotlib==3.10.3
    - mlflow==2.22.0
    - mlflow-skinny==2.22.0
    - opentelemetry-api==1.33.1
    - opentelemetry-sdk==1.33.1
    - opentelemetry-semantic-conventions==0.54b1
    - packaging==24.2
    - pandas==2.2.3
    - pip-chill==1.0.3
    - py3Dmol==2.5.3
    - pyarrow==19.0.1
    - pydantic==2.11.5
    - pydantic_core==2.33.2
    - python-dateutil==2.9.0.post0
    - requests==2.32.3
    - scikit-learn==1.6.1
    - smmap==5.0.2
    - sqlparse==0.5.3
    - starlette==0.46.2
    - threadpoolctl==3.6.0
    - tornado==6.5.1
    - tqdm==4.67.1
    - typing-inspection==0.4.1
    - tzdata==2025.2
    - uvicorn==0.34.2
    - vine==5.1.0

prefix: "/home/etri3060/.local/share/mamba/envs/guiddiffsbdd"
